/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2016-11-17 07:23:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1472888236000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String contextPath = request.getContextPath();
    request.setAttribute("contextPath", contextPath);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/newadd.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>增加员工信息</title>\r\n");
      out.write("<style>\r\n");
      out.write(".table th, .table td {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"height:50px;line-height:50px;font-size:25px;vertical-align: middle;text-align: center\" class=\"bg-primary\">XXX影院管理系统</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\" style=\"padding:10px 10px\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 左导航栏 -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/newadd.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>员工信息</title>\r\n");
      out.write("<style>\r\n");
      out.write(".table th, .table td {  \r\n");
      out.write("text-align: center;\r\n");
      out.write("height:30px;\r\n");
      out.write("} \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t  <div class=\"panel-heading\">\r\n");
      out.write("\t\t\t    <h3 class=\"panel-title\">导航</h3>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t<tr><td><img src=\"images/renyuan.png\" width=\"24px\">&nbsp;&nbsp;<a href=\"index.jsp\">员工管理</a></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><img src=\"images/renyuan.png\" width=\"24px\">&nbsp;&nbsp;<a href=\"index1.jsp\">员工分页</a></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><img src=\"images/yingting.png\" width=\"24px\">&nbsp;&nbsp;<a href=\"javascript:alert('你们自己做!')\">影厅管理</a></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><img src=\"images/zuowei.png\" width=\"24px\">&nbsp;&nbsp;<a href=\"javascript:alert('你们自己做!')\">座位管理</a></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><img src=\"images/yingpian.png\" width=\"24px\">&nbsp;&nbsp;<a href=\"javascript:alert('可以不用做!')\">影片管理</a></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><img src=\"images/dingpiao.png\" width=\"24px\">&nbsp;&nbsp;<a href=\"javascript:alert('可以不用做!')\">订票管理</a></td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 增加员工信息 -->\r\n");
      out.write("\t\t<div class=\"col-md-10\" style=\"padding-top:10px\">\r\n");
      out.write("\t\t\t<form class=\"form-horizontal\" role=\"form\" action=\"EmployeeServlet?method=add\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"emp_no\" class=\"col-sm-2 control-label\">用户编号</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"emp_no\" name=\"emp_no\" \r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"请输入大小写字母和数字,长度6-20位\" pattern=\"[a-zA-Z0-9]{6,20}\" \r\n");
      out.write("\t\t\t\t\t\t\trequired=\"required\" oninvalid=\"setCustomValidity('请输入大小写字母和数字,长度6-20位!')\" \r\n");
      out.write("\t\t\t\t\t\t\toninput=\"setCustomValidity('')\" >\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"emp_name\" class=\"col-sm-2 control-label\">用户姓名</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"emp_name\" name=\"emp_name\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"请输入真实姓名,10字以内\" pattern=\"[\\u4e00-\\u9fa5]{2,10}\"\r\n");
      out.write("\t\t\t\t\t\t\trequired=\"required\" oninvalid=\"setCustomValidity('请输入真实姓名,10字以内!')\"\r\n");
      out.write("\t\t\t\t\t\t\toninput=\"setCustomValidity('')\" >\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"emp_tel_num\" class=\"col-sm-2 control-label\">电话号码</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"tel\" class=\"form-control\" id=\"emp_tel_num\" name=\"emp_tel_num\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"请输入手机号码\" pattern=\"1[3-8][0-9]{9}\" \r\n");
      out.write("\t\t\t\t\t\t\trequired=\"required\" oninvalid=\"setCustomValidity('请输入正确手机号码!')\"\r\n");
      out.write("\t\t\t\t\t\t\toninput=\"setCustomValidity('')\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"emp_addr\" class=\"col-sm-2 control-label\">地址</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"emp_addr\" name=\"emp_addr\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"请输入地址\" pattern=\".{2,30}\" \r\n");
      out.write("\t\t\t\t\t\t\trequired=\"required\" oninvalid=\"setCustomValidity('请输入地址!')\"\r\n");
      out.write("\t\t\t\t\t\t\toninput=\"setCustomValidity('')\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"emp_email\" class=\"col-sm-2 control-label\">邮箱</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" id=\"emp_email\" name=\"emp_email\" \r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"请输入Email\" required=\"required\"  \r\n");
      out.write("\t\t\t\t\t\t\tpattern=\"([a-zA-Z0-9_-])+@[a-zA-Z0-9_-]+((\\.[a-z]{2,3}){1,2})\"\r\n");
      out.write("\t\t\t\t\t\t\toninvalid=\"setCustomValidity('请输入正确格式Email!')\"\r\n");
      out.write("\t\t\t\t\t\t\toninput=\"setCustomValidity('')\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2 control-label\" style=\"color:red;font-weight: bold;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <input type=\"hidden\" name=\"method\" value=\"add\"> -->\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">提  交</button>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
